/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as InteligenciaRouteImport } from './routes/inteligencia'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendedorOwnerIdRouteImport } from './routes/vendedor.$ownerId'
import { Route as ApiPublicUseSistemasRouteImport } from './routes/api/public/use-sistemas'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaRoute = InteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorOwnerIdRoute = VendedorOwnerIdRouteImport.update({
  id: '/vendedor/$ownerId',
  path: '/vendedor/$ownerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUseSistemasRoute = ApiPublicUseSistemasRouteImport.update({
  id: '/api/public/use-sistemas',
  path: '/api/public/use-sistemas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/integracoes': typeof IntegracoesRoute
  '/inteligencia': typeof InteligenciaRoute
  '/produtos': typeof ProdutosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendedor/$ownerId': typeof VendedorOwnerIdRoute
  '/api/public/use-sistemas': typeof ApiPublicUseSistemasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/integracoes': typeof IntegracoesRoute
  '/inteligencia': typeof InteligenciaRoute
  '/produtos': typeof ProdutosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendedor/$ownerId': typeof VendedorOwnerIdRoute
  '/api/public/use-sistemas': typeof ApiPublicUseSistemasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/integracoes': typeof IntegracoesRoute
  '/inteligencia': typeof InteligenciaRoute
  '/produtos': typeof ProdutosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vendedor/$ownerId': typeof VendedorOwnerIdRoute
  '/api/public/use-sistemas': typeof ApiPublicUseSistemasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/integracoes'
    | '/inteligencia'
    | '/produtos'
    | '/sitemap.xml'
    | '/vendedor/$ownerId'
    | '/api/public/use-sistemas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/integracoes'
    | '/inteligencia'
    | '/produtos'
    | '/sitemap.xml'
    | '/vendedor/$ownerId'
    | '/api/public/use-sistemas'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/integracoes'
    | '/inteligencia'
    | '/produtos'
    | '/sitemap.xml'
    | '/vendedor/$ownerId'
    | '/api/public/use-sistemas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  IntegracoesRoute: typeof IntegracoesRoute
  InteligenciaRoute: typeof InteligenciaRoute
  ProdutosRoute: typeof ProdutosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VendedorOwnerIdRoute: typeof VendedorOwnerIdRoute
  ApiPublicUseSistemasRoute: typeof ApiPublicUseSistemasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia': {
      id: '/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof InteligenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor/$ownerId': {
      id: '/vendedor/$ownerId'
      path: '/vendedor/$ownerId'
      fullPath: '/vendedor/$ownerId'
      preLoaderRoute: typeof VendedorOwnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/use-sistemas': {
      id: '/api/public/use-sistemas'
      path: '/api/public/use-sistemas'
      fullPath: '/api/public/use-sistemas'
      preLoaderRoute: typeof ApiPublicUseSistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  IntegracoesRoute: IntegracoesRoute,
  InteligenciaRoute: InteligenciaRoute,
  ProdutosRoute: ProdutosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VendedorOwnerIdRoute: VendedorOwnerIdRoute,
  ApiPublicUseSistemasRoute: ApiPublicUseSistemasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
