/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlaWatchdogRouteImport } from './routes/sla-watchdog'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuarentenaRouteImport } from './routes/quarentena'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as OrquestracaoRouteImport } from './routes/orquestracao'
import { Route as InteligenciaRouteImport } from './routes/inteligencia'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GovernancaRouteImport } from './routes/governanca'
import { Route as ExecutivoRouteImport } from './routes/executivo'
import { Route as ExcecoesRouteImport } from './routes/excecoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CloudReadinessRouteImport } from './routes/cloud-readiness'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendedorOwnerIdRouteImport } from './routes/vendedor.$ownerId'
import { Route as ApiV1IngestRouteImport } from './routes/api/v1/ingest'
import { Route as ApiPublicUseSistemasRouteImport } from './routes/api/public/use-sistemas'
import { Route as ApiPublicCatalogRouteImport } from './routes/api/public/catalog'
import { Route as ApiPublicErpIngestRouteImport } from './routes/api/public/erp.ingest'

const SlaWatchdogRoute = SlaWatchdogRouteImport.update({
  id: '/sla-watchdog',
  path: '/sla-watchdog',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuarentenaRoute = QuarentenaRouteImport.update({
  id: '/quarentena',
  path: '/quarentena',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrquestracaoRoute = OrquestracaoRouteImport.update({
  id: '/orquestracao',
  path: '/orquestracao',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaRoute = InteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernancaRoute = GovernancaRouteImport.update({
  id: '/governanca',
  path: '/governanca',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutivoRoute = ExecutivoRouteImport.update({
  id: '/executivo',
  path: '/executivo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcecoesRoute = ExcecoesRouteImport.update({
  id: '/excecoes',
  path: '/excecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudReadinessRoute = CloudReadinessRouteImport.update({
  id: '/cloud-readiness',
  path: '/cloud-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorOwnerIdRoute = VendedorOwnerIdRouteImport.update({
  id: '/vendedor/$ownerId',
  path: '/vendedor/$ownerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IngestRoute = ApiV1IngestRouteImport.update({
  id: '/api/v1/ingest',
  path: '/api/v1/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUseSistemasRoute = ApiPublicUseSistemasRouteImport.update({
  id: '/api/public/use-sistemas',
  path: '/api/public/use-sistemas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCatalogRoute = ApiPublicCatalogRouteImport.update({
  id: '/api/public/catalog',
  path: '/api/public/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicErpIngestRoute = ApiPublicErpIngestRouteImport.update({
  id: '/api/public/erp/ingest',
  path: '/api/public/erp/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/auditoria': typeof AuditoriaRoute
  '/cloud-readiness': typeof CloudReadinessRoute
  '/compliance': typeof ComplianceRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/excecoes': typeof ExcecoesRoute
  '/executivo': typeof ExecutivoRoute
  '/governanca': typeof GovernancaRoute
  '/inbox': typeof InboxRoute
  '/integracoes': typeof IntegracoesRoute
  '/inteligencia': typeof InteligenciaRoute
  '/orquestracao': typeof OrquestracaoRoute
  '/produtos': typeof ProdutosRoute
  '/quarentena': typeof QuarentenaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sla-watchdog': typeof SlaWatchdogRoute
  '/vendedor/$ownerId': typeof VendedorOwnerIdRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/use-sistemas': typeof ApiPublicUseSistemasRoute
  '/api/v1/ingest': typeof ApiV1IngestRoute
  '/api/public/erp/ingest': typeof ApiPublicErpIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/auditoria': typeof AuditoriaRoute
  '/cloud-readiness': typeof CloudReadinessRoute
  '/compliance': typeof ComplianceRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/excecoes': typeof ExcecoesRoute
  '/executivo': typeof ExecutivoRoute
  '/governanca': typeof GovernancaRoute
  '/inbox': typeof InboxRoute
  '/integracoes': typeof IntegracoesRoute
  '/inteligencia': typeof InteligenciaRoute
  '/orquestracao': typeof OrquestracaoRoute
  '/produtos': typeof ProdutosRoute
  '/quarentena': typeof QuarentenaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sla-watchdog': typeof SlaWatchdogRoute
  '/vendedor/$ownerId': typeof VendedorOwnerIdRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/use-sistemas': typeof ApiPublicUseSistemasRoute
  '/api/v1/ingest': typeof ApiV1IngestRoute
  '/api/public/erp/ingest': typeof ApiPublicErpIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/auditoria': typeof AuditoriaRoute
  '/cloud-readiness': typeof CloudReadinessRoute
  '/compliance': typeof ComplianceRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/excecoes': typeof ExcecoesRoute
  '/executivo': typeof ExecutivoRoute
  '/governanca': typeof GovernancaRoute
  '/inbox': typeof InboxRoute
  '/integracoes': typeof IntegracoesRoute
  '/inteligencia': typeof InteligenciaRoute
  '/orquestracao': typeof OrquestracaoRoute
  '/produtos': typeof ProdutosRoute
  '/quarentena': typeof QuarentenaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sla-watchdog': typeof SlaWatchdogRoute
  '/vendedor/$ownerId': typeof VendedorOwnerIdRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/use-sistemas': typeof ApiPublicUseSistemasRoute
  '/api/v1/ingest': typeof ApiV1IngestRoute
  '/api/public/erp/ingest': typeof ApiPublicErpIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/auditoria'
    | '/cloud-readiness'
    | '/compliance'
    | '/configuracoes'
    | '/dashboard'
    | '/excecoes'
    | '/executivo'
    | '/governanca'
    | '/inbox'
    | '/integracoes'
    | '/inteligencia'
    | '/orquestracao'
    | '/produtos'
    | '/quarentena'
    | '/sitemap.xml'
    | '/sla-watchdog'
    | '/vendedor/$ownerId'
    | '/api/public/catalog'
    | '/api/public/use-sistemas'
    | '/api/v1/ingest'
    | '/api/public/erp/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/auditoria'
    | '/cloud-readiness'
    | '/compliance'
    | '/configuracoes'
    | '/dashboard'
    | '/excecoes'
    | '/executivo'
    | '/governanca'
    | '/inbox'
    | '/integracoes'
    | '/inteligencia'
    | '/orquestracao'
    | '/produtos'
    | '/quarentena'
    | '/sitemap.xml'
    | '/sla-watchdog'
    | '/vendedor/$ownerId'
    | '/api/public/catalog'
    | '/api/public/use-sistemas'
    | '/api/v1/ingest'
    | '/api/public/erp/ingest'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/auditoria'
    | '/cloud-readiness'
    | '/compliance'
    | '/configuracoes'
    | '/dashboard'
    | '/excecoes'
    | '/executivo'
    | '/governanca'
    | '/inbox'
    | '/integracoes'
    | '/inteligencia'
    | '/orquestracao'
    | '/produtos'
    | '/quarentena'
    | '/sitemap.xml'
    | '/sla-watchdog'
    | '/vendedor/$ownerId'
    | '/api/public/catalog'
    | '/api/public/use-sistemas'
    | '/api/v1/ingest'
    | '/api/public/erp/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  AuditoriaRoute: typeof AuditoriaRoute
  CloudReadinessRoute: typeof CloudReadinessRoute
  ComplianceRoute: typeof ComplianceRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  ExcecoesRoute: typeof ExcecoesRoute
  ExecutivoRoute: typeof ExecutivoRoute
  GovernancaRoute: typeof GovernancaRoute
  InboxRoute: typeof InboxRoute
  IntegracoesRoute: typeof IntegracoesRoute
  InteligenciaRoute: typeof InteligenciaRoute
  OrquestracaoRoute: typeof OrquestracaoRoute
  ProdutosRoute: typeof ProdutosRoute
  QuarentenaRoute: typeof QuarentenaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlaWatchdogRoute: typeof SlaWatchdogRoute
  VendedorOwnerIdRoute: typeof VendedorOwnerIdRoute
  ApiPublicCatalogRoute: typeof ApiPublicCatalogRoute
  ApiPublicUseSistemasRoute: typeof ApiPublicUseSistemasRoute
  ApiV1IngestRoute: typeof ApiV1IngestRoute
  ApiPublicErpIngestRoute: typeof ApiPublicErpIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sla-watchdog': {
      id: '/sla-watchdog'
      path: '/sla-watchdog'
      fullPath: '/sla-watchdog'
      preLoaderRoute: typeof SlaWatchdogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quarentena': {
      id: '/quarentena'
      path: '/quarentena'
      fullPath: '/quarentena'
      preLoaderRoute: typeof QuarentenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orquestracao': {
      id: '/orquestracao'
      path: '/orquestracao'
      fullPath: '/orquestracao'
      preLoaderRoute: typeof OrquestracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia': {
      id: '/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof InteligenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governanca': {
      id: '/governanca'
      path: '/governanca'
      fullPath: '/governanca'
      preLoaderRoute: typeof GovernancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executivo': {
      id: '/executivo'
      path: '/executivo'
      fullPath: '/executivo'
      preLoaderRoute: typeof ExecutivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excecoes': {
      id: '/excecoes'
      path: '/excecoes'
      fullPath: '/excecoes'
      preLoaderRoute: typeof ExcecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud-readiness': {
      id: '/cloud-readiness'
      path: '/cloud-readiness'
      fullPath: '/cloud-readiness'
      preLoaderRoute: typeof CloudReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor/$ownerId': {
      id: '/vendedor/$ownerId'
      path: '/vendedor/$ownerId'
      fullPath: '/vendedor/$ownerId'
      preLoaderRoute: typeof VendedorOwnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/ingest': {
      id: '/api/v1/ingest'
      path: '/api/v1/ingest'
      fullPath: '/api/v1/ingest'
      preLoaderRoute: typeof ApiV1IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/use-sistemas': {
      id: '/api/public/use-sistemas'
      path: '/api/public/use-sistemas'
      fullPath: '/api/public/use-sistemas'
      preLoaderRoute: typeof ApiPublicUseSistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog': {
      id: '/api/public/catalog'
      path: '/api/public/catalog'
      fullPath: '/api/public/catalog'
      preLoaderRoute: typeof ApiPublicCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/erp/ingest': {
      id: '/api/public/erp/ingest'
      path: '/api/public/erp/ingest'
      fullPath: '/api/public/erp/ingest'
      preLoaderRoute: typeof ApiPublicErpIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  AuditoriaRoute: AuditoriaRoute,
  CloudReadinessRoute: CloudReadinessRoute,
  ComplianceRoute: ComplianceRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  ExcecoesRoute: ExcecoesRoute,
  ExecutivoRoute: ExecutivoRoute,
  GovernancaRoute: GovernancaRoute,
  InboxRoute: InboxRoute,
  IntegracoesRoute: IntegracoesRoute,
  InteligenciaRoute: InteligenciaRoute,
  OrquestracaoRoute: OrquestracaoRoute,
  ProdutosRoute: ProdutosRoute,
  QuarentenaRoute: QuarentenaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlaWatchdogRoute: SlaWatchdogRoute,
  VendedorOwnerIdRoute: VendedorOwnerIdRoute,
  ApiPublicCatalogRoute: ApiPublicCatalogRoute,
  ApiPublicUseSistemasRoute: ApiPublicUseSistemasRoute,
  ApiV1IngestRoute: ApiV1IngestRoute,
  ApiPublicErpIngestRoute: ApiPublicErpIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
